# Generated by Django 5.1.4 on 2024-12-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
