# Generated by Django 5.1.1 on 2024-12-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_remove_goal_completed_remove_goal_priority_goalpair'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='times_chosen',
            field=models.SmallIntegerField(default=0),
        ),
    ]
