# Generated by Django 5.1.1 on 2024-12-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_goal_times_chosen'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='times_seen',
            field=models.SmallIntegerField(default=0),
        ),
    ]
